### ISSUE TITLE
No text showing in editor.

### ISSUE THREAD

**Issue by Thontin** [pyzo/pyzo#1064] opened 2024-08-24 15:32 UTC
Line numbers show but no text showing in editor. No text in tooltips. Nothing can be selected; seems that the fields are empty.
Text does show in  file Browser so can navigate ok. Pyzo 4.11.2 installed today on Linux Mint 21.3 Cinnamon with 'sudo apt install pyzo'. 
What must I do to invoke text ?

**Comment by bdieterm** [comment] 2024-08-24 15:44
Pyzo 4.11.2 is quite outdated -- it was released 4 years ago.
Please try the newest version v4.16.0: https://github.com/pyzo/pyzo/releases/tag/v4.16.0
If the binary in the [.tar.gz archive](https://github.com/pyzo/pyzo/releases/download/v4.16.0/pyzo-4.16.0-linux_x86_64.tar.gz) does not work, then there is still the option to download Pyzo's source code and run it from source: Just extract the downloaded [source code](https://github.com/pyzo/pyzo/archive/refs/heads/main.zip) and run
`python3 /path/to/pyzo-main/pyzolauncher.py`. You need one of these 4 Qt Python wrappers: PySide6, PyQt6, PySide2, PyQt5.
Does this solve the problem for you?

**Comment by Thontin** [comment] 2024-08-25 12:02
Will try the .tar.gz new version v4.16.0, downloading very slowly. Will report. OK

**Comment by Thontin** [comment] 2024-08-26 07:10
Partial success. I installed the new version 4.16.0 ok. Which opens and looks good but my 'helloworld.py' does not run. There is a Shell error message:

"Python 3.10.12 (main, Jul 29 2024, 16:56:48) on linux (64 bits).
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)

The kernel process exited. (134) "

I will have another go at it later. Uninstall. Reinstall.

**Comment by bdieterm** [comment] 2024-08-26 14:42
This looks like a missing package in Linux Mint.
Try to (re-)install it by executing the line
`sudo apt-get install --reinstall libxcb-xinerama0`
in a terminal.

If this does not solve the problem, then add the line `QT_DEBUG_PLUGINS=1` to the "environ" textbox in Pyzo's shell configuration dialog and then restart the shell to see more details.

**Comment by bdieterm** [comment] 2024-09-10 17:33
> qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""

Today I also had such an error in the shell when I started Pyzo v4.16.0 via Linux binaries on a computer with a Kubuntu 24.04 live system (booted via pen drive). The reason for the error was some library conflict when Pyzo detected a PyQt5 wrapper in the shell with system's Python interpreter and tried to create a QApplication object. Setting the "gui" parameter in the shell configuration to "Asyncio" instead of "Auto" worked, but the downside is that there is no support for GUI event loops in the shell.

Therefore I tested two other workarounds:

Adding the PyQt6 package to the system's Python interpreter via
`$ sudo apt-get install python3-pyqt6`
Then Pyzo used the PyQt6 event loop in the shell with the system's Python interpreter.
But this also has a downside: You cannot use PyQt5.


My recommended solution is to run Pyzo from source code:

Download Pyzo's source via
https://github.com/pyzo/pyzo/archive/refs/heads/main.zip
and extract the archive to any folder.
Then run
`$ python3 /path/to/pyzo-main/pyzolauncher.py`
This worked out of the box with the Kubuntu 24.04 live system, by the way.

If you do not have a Qt wrapper package installed (one of PySide6, PyQt6, PySide2, PyQt5), then install one, for example via
`$ sudo apt-get install python3-pyqt6`
or
`$ sudo apt-get install python3-pyqt5`

**Comment by bdieterm** [comment] 2024-09-20 20:39
@Thontin: Do you still have the problem when starting Pyzo?

**Comment by Charlignon** [comment] 2024-10-01 11:24
I experienced an issue similar to the one described in the first message: installing Pyzo 4.16.0 & QT6 on linux resulted in the editor not displaying any text. I was able to solve it by using PySide6 instead of QT6. You'll find below what I tried. All snippets assume the environment is cleaned/all is uninstalled between attempts.
### What didn't work
```sh
# Classic apt install
sudo apt install python3-pyqt6
sudo apt install pyzo
pyzo # --> empty code editor 
```
```sh
# Same but with QT5 instead
sudo apt install python3-pyqt6
sudo apt install pyzo
pyzo # --> pyzo not starting
```
```sh
# I use `pipx` to install apps in venvs, but it's basically the same as doing `python3 -m pip ...`
pipx install pyzo
pipx inject pyzo pyqt6 # to install package in the same venv
pyzo # --> again empty code editor
```
### What worked
```sh
pipx install pyzo
pipx inject pyzo pyside6
pyzo
```

### Notes
It seems that the issue is with the QT6 lib. I assume that an apt install would work as well - although I couldn't find `python3-pyside6` nor `pyside6` packages.
I did noticed a lot of repeated error logs in console while running with QT6, I'll include an excerpt below, if this can help anyone investigate a potential bug.
<details><summary>Console errors when running Pyzo 4.16.0 with pyqt6</summary>

```sh
➜  ~ pyzo
Pyzo 4.16.0
Started our command server
Loaded theme 'Scintilla'
Loaded theme 'default_dark'
Loaded theme 'Default'
Loaded theme 'Solarized_Dark'
Loaded theme 'Solarized_Light'
Loaded theme 'Dark'
Uncaught Python exception: type object 'Qt' has no attribute 'DotLine'
  File "/home/charles/.local/pipx/venvs/pyzo/lib/python3.12/site-packages/pyzo/codeeditor/extensions/appearance.py", line 474, in paintEvent
    super().paintEvent(event)
  File "/home/charles/.local/pipx/venvs/pyzo/lib/python3.12/site-packages/pyzo/codeeditor/extensions/appearance.py", line 132, in paintEvent
    super().paintEvent(event)
  File "/home/charles/.local/pipx/venvs/pyzo/lib/python3.12/site-packages/pyzo/codeeditor/extensions/appearance.py", line 413, in paintEvent
    super().paintEvent(event)
  File "/home/charles/.local/pipx/venvs/pyzo/lib/python3.12/site-packages/pyzo/codeeditor/extensions/appearance.py", line 556, in paintEvent
    super().paintEvent(event)
  File "/home/charles/.local/pipx/venvs/pyzo/lib/python3.12/site-packages/pyzo/codeeditor/extensions/appearance.py", line 505, in paintEvent
    super().paintEvent(event)
  File "/home/charles/.local/pipx/venvs/pyzo/lib/python3.12/site-packages/pyzo/codeeditor/extensions/appearance.py", line 584, in paintEvent
    super().paintEvent(event)
  File "/home/charles/.local/pipx/venvs/pyzo/lib/python3.12/site-packages/pyzo/codeeditor/extensions/appearance.py", line 661, in paintEvent
    pen.setStyle(format.linestyle)
                 ^^^^^^^^^^^^^^^^
  File "/home/charles/.local/pipx/venvs/pyzo/lib/python3.12/site-packages/pyzo/codeeditor/style.py", line 216, in linestyle
    self._linestyle = Qt.DotLine
                      ^^^^^^^^^^

QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?

# ... repeat "no attribute 'DotLine'" and "QBackingStore::endPaint()" indefinitely
```
</details>
It could be a good thing to update the [linux install guide](https://pyzo.org/install_linux.html) to remove mentions from libs that don't work (like QT5), and side note but the flatpak method is seriously outdated  (last build is 4.9 :p)

**Comment by bdieterm** [comment] 2024-10-01 17:12
As far as I can tell, this "no text showing in editor" is a consequence of a bug with Qt enums.
To reproduce this problem with Pyzo v4.16.0 I had to use PyQt6 as a Qt-wrapper and I had to use the "default_dark" style (instead of the "default" style). This resulted in dark text on dark background.

I already fixed that bug three weeks ago via #1069, but this was after Pyzo v4.16.0 was released.
@almarklein: I think it's a good time for a new release.

@Charlignon:
If you want to test this before the new release, just download the [newest source code](https://github.com/pyzo/pyzo/archive/refs/heads/main.zip), extract folder "pyzo-main/pyzo" and use this folder to replace folder "/home/charles/.local/pipx/venvs/pyzo/lib/python3.12/site-packages/pyzo".
Please report back if this solved the problem so that we can close this issues.

> It could be a good thing to update the [linux install guide](https://pyzo.org/install_linux.html) to remove mentions from libs that don't work (like QT5), and side note but the flatpak method is seriously outdated (last build is 4.9 :p) 

Qt5 wrappers (PySide2 and PyQt5) normally work with Pyzo, at least when running Pyzo from source. The binary distribution of Pyzo comes with its own PyQt5 library and that normally causes conflicts on newer Linux versions -- this is a general problem when distributing applications for Linux and not the fault of Qt5.

You are right that the installation instructions on pyzo.org are outdated.
I recently reworked the installation instructions in the Readme.md file, see here:
https://github.com/pyzo/pyzo#installation
This Readme.md is up to date.

**Comment by Charlignon** [comment] 2024-10-05 08:56
Thank you for your indications ! I tested a clean install from source code, and I confirm that it works as expected with `PyQt6`, hence the issue can be marked as resolved.
> and that normally causes conflicts on newer Linux version
Indeed I forgot to take that into account. I had many troubles with python after upgrading to the latest ubuntu, that was a key reason to install Pyzo in the first place ! I first used Pyzo 11 years ago when I started programming,

**Comment by bdieterm** [comment] 2024-10-06 07:46
You are welcome. Thank you for the kind words.

**Closed by bdieterm** 2024-10-06 07:46 UTC

**Comment by almarklein** [comment] 2024-10-07 12:09
> @almarklein: I think it's a good time for a new release.

I'll roll a new release. I'm super-amazed by the many improvements you did again ... 🚀
