### ISSUE TITLE
No tooltips in 4.2.1

### ISSUE THREAD

**Issue by ysalmon** [pyzo/pyzo#419] opened 2016-08-11 14:40 UTC
I have just installed pyzo 4.2.1 (Linux 64 binaries from pyzo.org).
The nice tooltips that used to appear when typing the name of a function, indicatinf its parameters, appear no more !
The general help tooltips that appear when the mouse hovers over something (menu item, etc.) still do.

**Comment by ysalmon** [comment] 2016-08-11 14:48
In fact, Python's help system seems broken : typing ```help([])``` for example in the IEP console gives no answer (the call does not terminate).
This is with miniconda and both with and without IPython activated.

Running the same python3 interpreter in a system shell, I can do ```help([])``` with no problem.

**Comment by draustin** [comment] 2016-08-18 13:47
I reproduced both problems on 4.2.1 (installed via pip, Ubuntu 64 bit).
After uninstalling and reinstalling version 4.1, both problems went away.

**Comment by almarklein** [comment] 2016-08-19 08:07
Reproduced. Calltips were broken due to the introduction of the Parenthesis token in the parser. Fixed in https://github.com/pyzo/pyzo/commit/0dc136d931d3ba8dc3df9572b5b953cffa5c3fa2. Thanks for reporting.

Not sure why `help([])` breaks. This seems an unrelated issue. Pleas open a new issue for that if it persists.

**Closed by almarklein** 2016-08-19 08:07 UTC
