### ISSUE TITLE
Keyboard shortcuts not working on Linux with Pyqt5

### ISSUE THREAD

**Issue by maria8899** [pyzo/pyzo#470] opened 2017-02-22 18:43 UTC
Hi,
I cannot copy and paste code using the keyboard within the editor or from editor to shell.

Version info
Pyzo version: 4.3.1 (source)
Platform: linux
Python version: 3.5.2+
Qt version: 5.8.0
PyQt5 version: 5.8

Pyzo directories
Pyzo source directory: /usr/local/lib/python3.5/dist-packages/pyzo
Pyzo userdata directory: /home/maria/.pyzo

Any idea why?

**Comment by almarklein** [comment] 2017-02-24 10:47
This has recently been reported: https://groups.google.com/forum/#!topic/pyzo/HFoBWJ97zsg

It seems to be an issue related to a new version in Qt or PyQt. Maybe a certain part of the API changed, breaking our copy-paste functionality.

**Comment by almarklein** [comment] 2017-02-24 11:04
Spun up a Linux VM.

With Python provided by miniconda, I don't see the problem. Version info:
Pyzo version: 4.3.1 (source)
Platform: linux
Python version: 3.5.3
Qt version: 5.6.2
PyQt5 version: 5.6

With the system Python and Pyqt5, I can reproduce the problem. Versiom info:
Pyzo version: 4.3.1 (source)
Platform: linux
Python version: 3.4.3
Qt version: 5.2.1
PyQt5 version: 5.2.1

So it seems to be related to PyQt5, though oddly enough the problem does not seem to happen with miniconda/anaconda. It does not seem to be related to a specific version of qt5 though; Maria's qt version and my qt version differ quite a bit, and my miniconda version is in between them.

As a workaround, one can switch to using Pyqt4, by `apt-get install python3-pyqt4`, and `export QT_API=pyqt4`. Or one can use the miniconda/anaconda interpreter to launch Pyzo.

**Comment by almarklein** [comment] 2017-02-24 11:09
Actually, this is not specific to copy-paste, but to *all* shortcuts.

**Comment by almarklein** [comment] 2017-02-24 11:52
Fixed by https://github.com/pyzo/pyzo/commit/0064a5c709e4c5f6f67832128f022469c637a4c2

This Qt problem has been reported before (http://stackoverflow.com/questions/23916623/qt5-doesnt-recognised-shortcuts-unless-actions-are-added-to-a-toolbar). There its described as a bug, but since its still there in qt 5.8, its more like a backward incompatible change.

People suffering from this bug can add that line to their local version of Pyzo.

**Closed by almarklein** 2017-02-24 11:52 UTC

**Comment by maria8899** [comment] 2017-02-24 12:06
Great, adding the line has fixed this issue. Thank you!
