### ISSUE TITLE
Locked widgets layout

### ISSUE THREAD

**Issue by ghisvail** [pyzo/pyzo#443] opened 2016-09-30 13:07 UTC
Since pyzo v4.3.x, the layout of the widgets cannot be changed. New widgets can be added via the `tools` menu, but their location cannot be changed. I can drag them to a new position but instead of sticking to it, the widget comes right back to where it was, hence the locking.

This happens on both the packaged version on Debian unstable or on a virtualenv.

One can easily reproduce this by running:

```
pip install pyzo qtpy pyqt5
```

on a fresh virtualenv:

```
pyvenv pyzo && source pyzo/bin/activate
```

**Comment by ghisvail** [comment] 2016-10-04 18:46
Can anyone confirm this please?

**Comment by almarklein** [comment] 2016-10-04 21:37
I cannot reproduce this. Really odd behavior...

**Comment by ghisvail** [comment] 2016-10-05 18:37
Are there any other config files written apart from `~/.pyzo`. I tried removing this folder and starting afresh, but the layout of the widgets still cannot be changed. Again, the symptoms are that each widget can be individually dragged around the GUI, but none of them can *hook* to a new location. Instead the widget goes back to its original location.

**Comment by ghisvail** [comment] 2016-10-05 18:51
But you are correct, I cannot reproduce this problem with a workstation running Ubuntu 14.04 with a `virtualenv` containing `pyzo` and `pyside`. So it should be specific to `pyqt5` / `qt5`.

**Comment by almarklein** [comment] 2016-10-05 20:54
> Are there any other config files written apart from ~/.pyzo?

Apart from `qt.conf` in the frozen directory, no.

**Comment by ghisvail** [comment] 2016-10-06 11:17
And I can't test other backends since Debian Stretch now is on Python 3.5 and neither `pyqt` (dropped) nor `pyside` (python<=3.4) are installable with `pip` anymore. Any idea how I could debug this @almarklein ?

**Comment by almarklein** [comment] 2016-10-06 19:23
I'm in the dark as much as you are :/

**Comment by ghisvail** [comment] 2016-10-13 14:13
I have investigated this further and found out that this problem only arises with recent versions of PyQt5, like the one currently shipped in Debian testing (5.7).

This issue does not happen if `pyzo` is run with a Qt4 API via `QT_API=pyqt pyzo` or `QT_API=pyside pyzo`. There are also no problems with PyQt5 on Debian stable (5.3). 

@almarklein 
When you said you tried Ubuntu 16.04, how did you do it?

**Comment by ghisvail** [comment] 2016-10-13 14:28
And another observation (still on Debian testing), the issue is reproduced if I install `pyzo` with:
```
pip install pyzo qtpy pyqt5==5.7
```
but **not** reproduced with:
```
pip install pyzo qtpy pyqt5==5.6
```
So it could well be a regression from PyQt5 v5.7, but it'd be nice to confirm this elsewhere.

**Comment by almarklein** [comment] 2016-10-13 19:22
I tested using conda, which pyqt5 version is 5.6.0. So that would explain it. Users (and myself) are also experiencing problems with PyQt5 on Windows. I think I'll switch back to PySide for the binaries for now ...

**Comment by ghisvail** [comment] 2016-10-13 19:27
The problem is that neither PyQt4 nor PySide are available on PyPI with Python 3.5 onwards. Do you know whether the Anaconda folks are planning to maintain / provide both PyQt4 backends for much longer?

**Comment by almarklein** [comment] 2016-10-13 19:35
@ccordoba12 might know.

**Comment by ccordoba12** [comment] 2016-10-13 22:49
Continuum's PyQt4 packages will be in our repos forever :-)

**Comment by ghisvail** [comment] 2016-10-14 09:59
Forwarded upstream: https://www.riverbankcomputing.com/pipermail/pyqt/2016-October/038209.html

**Comment by The-Compiler** [comment] 2016-10-14 11:38
Note PyQt is only a wrapper over Qt - this smells more like a Qt bug than a PyQt one.

**Comment by snarkturne** [comment] 2016-10-18 16:52
Hi,
Exactly the same problem here on Arch Linux :
```
> yaourt -Q | grep pyqt
extra/pyqt4-common 4.11.4-4
extra/pyqt5-common 5.7-2
extra/python-pyqt4 4.11.4-4
extra/python-pyqt5 5.7-2
```
```
> pip freeze | grep pyzo
pyzo==4.3.1
```

Python version : 3.5.2

**Comment by ghisvail** [comment] 2016-11-23 11:48
The problem seems to have disappeared with the transition to Qt 5.7 in the Debian archive. No idea what happened.

**Comment by almarklein** [comment] 2017-07-03 11:27
Closing, as this appears to be resolved, and is upstream anyway.

**Closed by almarklein** 2017-07-03 11:27 UTC
Labels: Qt-specific, type: bug
