### ISSUE TITLE
Usual shortcut for { make ( with Pyzo 4.10.2)

### ISSUE THREAD

**Issue by jowe19** [pyzo/pyzo#711] opened 2020-09-03 08:45 UTC
The usual shortcut for "{" in macOS (Option +/ () make "(" with Pyzo 4.10.2, instead of {. 

How can I fix it ?

**Comment by almarklein** [comment] 2020-09-07 14:46
Does the behavior change when turning off `Settings > autocompletion >Auto close brackets` (last option)?

**Comment by jowe19** [comment] 2020-09-07 16:36
Yes, it does.
The bracket appears whenever the "Auto close brackets" option is disabled.

**Comment by almarklein** [comment] 2020-09-07 19:38
> The bracket appears

The correct one, you mean? :)

**Comment by jowe19** [comment] 2020-09-07 19:56
Yes, the correct one.

**Comment by almarklein** [comment] 2020-09-07 20:02
Ok, so this looks like a duplicate of #662 ... I'd need to see if this can be fixed. In the mean while, you'd have to do without auto bracket closing...

**Closed** 2020-10-16 11:58 UTC
Labels: type: bug

**Comment by almarklein** [comment] 2020-10-16 12:00
Fixed in #726. Will a release soon (maybe today).
