### ISSUE TITLE
Help freezes shell

### ISSUE THREAD

**Issue by fstengel** [pyzo/pyzo#465] opened 2017-01-29 15:45 UTC
Using pyzo 4.3.1, when I type

`help(list)`

inside a shell running the latest anaconda python, the shell freezes. It looks as if the shell was trying to pretty print the result and the silently crashing. Of course, running the same python executable from the command line yields the expected result. I tried using an old all in one version and there is no visible problem.

**Version Info:**
Pyzo 4.3.1 downoladed from site
Platform: OSX 10.10
Python: 3.5.2 (anaconda)

**Comment by almarklein** [comment] 2017-01-31 10:57
This looks like a duplicate of #422, the [fix](https://github.com/pyzo/pyzo/commit/f047f0f11d85f169d157c7ea7570a54b94ad96c7) is perhaps not enough.

**Comment by almarklein** [comment] 2017-01-31 12:11
Oh wait, we have not had a release since that fix. I guess we need to do a release soonish.

**Comment by fstengel** [comment] 2017-01-31 13:33
The fix works. I did not search properly: I did not look if there was a closed issue similar to mine...

**Comment by almarklein** [comment] 2017-02-01 08:52
That's ok :)

**Closed by almarklein** 2017-02-01 08:52 UTC
