### ISSUE TITLE
help(something) blocks the shell on OSX with Pyzo 4.2.1 to 4.3.1

### ISSUE THREAD

**Issue by RivetBenoit** [pyzo/pyzo#458] opened 2016-12-14 08:50 UTC
Title says it all : help(anything) blocks the shell (whether using iPython on not) with Pyzo 4.3.1 on Mac OS X Sierra. For example :

>>>help(print)

doesn't show anything... and of course I can't use the shell anymore.

I can reproduce the bug with Pyzo 4.2.1 and Pyzo 4.3; however Pyzo 4.1 works fine.

**Comment by almarklein** [comment] 2016-12-14 13:49
Thanks for the report. I am happy to say that this is already fixed (duplicate of #422). Now to wait for the next release. In the mean time, you could apply this change to the code of your copy of Pyzo: https://github.com/pyzo/pyzo/commit/f047f0f11d85f169d157c7ea7570a54b94ad96c7

**Closed by almarklein** 2016-12-14 13:49 UTC
