### ISSUE TITLE
Failure of using all keyboard shortcuts

### ISSUE THREAD

**Issue by XuchanBao** [pyzo/pyzo#474] opened 2017-04-02 15:49 UTC
At some point after installing PyQt5, I noticed all keyboard shortcuts in pyzo editor or shell stopped working, including copy/paste, save, open etc. However, inside some pop-up windows (like settings and shell configuration), some shortcuts like Ctrl+C and Ctrl+V still works.

**Comment by XuchanBao** [comment] 2017-04-02 15:50
I tried uninstalling and reinstalling pyzo (in ubuntu VM using python3-pip), the issue persists.

**Comment by almarklein** [comment] 2017-04-02 20:35
duplicate of #470

**Closed by almarklein** 2017-04-02 20:35 UTC
