### ISSUE TITLE
Braces {} on Mac OS X with French keyboard layout

### ISSUE THREAD

**Issue by RivetBenoit** [pyzo/pyzo#562] opened 2018-10-05 09:57 UTC
I can't input braces with Pyzo 4.6.0 on Mac OS X High Sierra 10.13.6 : braces {} are changed to parentheses () whenever I try to input them using my keyboard.

There is no such problem with any other text editor (such as Textwrangler) and braces do appear when copying from another editor and pasting into the shell or the code editor.

**Comment by almarklein** [comment] 2018-10-05 13:43
Arg, sorry to hear that ... and thanks for reporting!

We've recently added autoclosing for brackets. We probably introduced this bug then. You can turn this new feature off using the Settings menu > Autocompletion > Autoclose brackets. That *should* fix things for your.

But that would not solve the bug. Do you see a difference between inputting a `{` and a `}`? Please try adding while text is selected, right before an existing `}`, in the middle of a word, and with whitespace on both sides. These different situations result in slightly different code paths, so if you could please report on those, it will hopefully help pinpoint the bug ...

Thanks

**Comment by almarklein** [comment] 2018-10-05 13:44
cc @kelsa-pi

**Comment by kelsa-pi** [comment] 2018-10-05 16:04
Hi,
I can't reproduce problem on Ubuntu. 

BTW [Unable to type braces and square braces in emacs](https://stackoverflow.com/questions/3376863/unable-to-type-braces-and-square-braces-in-emacs)

**Comment by RivetBenoit** [comment] 2018-10-05 17:05
> We've recently added autoclosing for brackets. We probably introduced this bug then. You can turn this new feature off using the Settings menu > Autocompletion > Autoclose brackets. That _should_ fix things for your.

Problem fixed when turning off autocompletion, thanks, braces are back.

> But that would not solve the bug. Do you see a difference between inputting a `{` and a `}`?

No difference.

> Please try adding while text is selected, right before an existing `}`, in the middle of a word, and with whitespace on both sides. These different situations result in slightly different code paths, so if you could please report on those, it will hopefully help pinpoint the bug ...

No difference either.

**Comment by RivetBenoit** [comment] 2018-10-05 17:18
Upon further investigation :
1. I don't reproduce the problem when using pyzo on windows
2. I don't reproduce the problem on Mac OS when changing the keyboard layout.

I am using a french keyboard layout : with this particular layout, the problem happens. However, when switching to an American or British keyboard layout, braces are back :-)

This seems to be the exact same issue as pointed out by kelsa-pi where a similar problem with the french keyboard is reported https://stackoverflow.com/a/9539179/5544109 and thus probably a specific bug due to this particular layout on Mac OS.

I guess me and other fellow french users can do without autocompletion on Mac OS...

**Comment by almarklein** [comment] 2018-10-08 09:03
@RivetBenoit Thanks for the feedback. Yeah, so it looks like an issue between Qt and the keyboard layout. Though since the default behavior (with the feature turned off) is ok, I wonder if we can fix it in Pyzo ...

When I have time, I'll grab my Mac from the closet and will try to see if there's a way around this. If someone beats me to it, that would be great :D  the code is [around here](https://github.com/pyzo/pyzo/blob/master/pyzo/codeeditor/extensions/behaviour.py#L489), in particular the usage of `event.key()`, maybe we need to look at another property of the event object ...

**Comment by almarklein** [comment] 2018-10-19 08:37
I tried looking into this using a Mac. But of course, my Mac does not actually have a French keyboard layout. So when I tell OS X to use a French layout, all keys are jumbled. Then my plan was to open a terminal an find the key that inserts a `{`, and then use the same key in Pyzo to see if I can reproduce it becoming `(`. Unfortunately, I was unable to find that key. And even then ... My Mac might simply not be affected by the bug.

**Comment by almarklein** [comment] 2020-10-16 12:33
This is fixed in #726. A release will follow soon (probably today).

**Closed** 2020-10-16 12:33 UTC
Labels: part: editor, type: bug
