### ISSUE TITLE
runaway memory leak

### ISSUE THREAD

**Issue by don6019** [pyzo/pyzo#816] opened 2022-10-21 04:06 UTC
Version info
Pyzo version: 4.12.3 (source)
Platform: linux
Python version: 3.9.12
Qt version: 5.15.2
PyQt5 version: 5.15.7
==================================================
I have a problem with Pyzo when using a particular python library - tinydb

In the pyzo shell - 

`>>> pip install tinydb
Collecting tinydb
  Using cached tinydb-4.7.0-py3-none-any.whl (24 kB)
Installing collected packages: tinydb
Successfully installed tinydb-4.7.0

`>>> from tinydb import TinyDB, Query

`>>> Q = Query()

`>>> `

This causes the python process to rapidly consume growing amounts of memory until the shell is restarted (before the system runs out of memory and freezes).
Same thing happens if I run the above in a script in the Pyzo editor.

If I start the python interpreter in a separate terminal window this does not happen, also does not happen in other IDE such as IDLE or Eclipse - only in Pyzo - strange ??

I have found the same problem using Pyzo on Windows (10) and Linux (ZorinOS 16.1)

Curious that it is only this particular library which causes a problem with Pyzo but nowhere else ??

I really love using Pyzo - it is far and away the best Python IDE I have found and use it almost everyday. Can anyone else duplicate this issue and or come up with a solution or work around.

Thanks for reading.

Don

**Comment by almarklein** [comment] 2022-10-21 08:26
> I really love using Pyzo - it is far and away the best Python IDE I have found and use it almost everyday.

❤️ 

> This causes the python process to rapidly consume growing amounts of memory until the shell is restarted (before the system runs out of memory and freezes).

That is strange indeed. I just tested on MacOS, and cannot reproduce. Will test on Windows later.

Do you have a GUI integration on? If so, could you try turning that to `None` in the shell config?

**Comment by don6019** [comment] 2022-10-21 09:50
Thanks for the reply.
Yes I did try with GUI set to None (and also some of the others). That didn't appear to make any difference unfortunately.

**Comment by don6019** [comment] 2022-10-21 22:59
I tried the modified introspection.py as proposed by adddvent and this does indeed appear to have solved my problem with TinyDB and Pyzo.

Thankyou very much.

**Comment by almarklein** [comment] 2022-10-22 08:10
Closed by #818

**Comment by almarklein** [comment] 2022-10-22 08:10
Thanks for reporting this and testing the proposed solution!

**Closed by almarklein** 2022-10-22 08:10 UTC
Labels: type: bug
