### ISSUE TITLE
Pyzo 4.2.1 takes 30 secs to start

### ISSUE THREAD

**Issue by ysalmon** [pyzo/pyzo#423] opened 2016-08-19 08:32 UTC
On my (recent) computer, Pyzo 4.2.1 takes 10 times more time to start than 4.1.1 (30 secs versus 3 secs).

This happens even if there is no .py file to reopen (so no reparsing time).

Starting 4.2.1 from the command line, I see the following trace immediately : 
```
yann@ysalm:/opt/yann/pyzo-4.2.1$ ./pyzo
Started our command server
Fontconfig error: Cannot load default config file
```
Then roughly 28 seconds elapse, then
```
Note about pyzolib.path - better use pathlib (part of py34)
```
and the main window appears quickly.

Starting 4.1.1 shows the following in a very short time before the main windows appears : 
```
yann@ysalm:/opt/yann/pyzo-4.1.1$ ./pyzo
Started our command server
Note about pyzolib.path - better use pathlib (part of py34)
```

**Comment by almarklein** [comment] 2016-09-04 09:18
> `Fontconfig error: Cannot load default config file`

mmm, probably related to #414 then.

**Comment by almarklein** [comment] 2016-09-04 09:19
What OS are you on?

**Comment by ysalmon** [comment] 2016-09-07 10:43
XUbuntu 16.04 64 bits.
I will come back to this problem in a few days after receiving a new computer and making a fresh OS install as I recently deployed Pyzo to computers at my school (Debian 8 32 bits) and they do not exhibit this behaviour.

**Comment by almarklein** [comment] 2016-09-07 13:07
FWIW I have been able to reproduce this. With a bit of luck this will be fixed if we update Qt, but other than that, I'm not sure what to do...

**Comment by ysalmon** [comment] 2016-09-07 20:53
This is on XUbuntu 16.04. This happens on a brand new system, on a brand new linux profile.

What dumbfounds me is that this does not occur with earlier versions of pyzo (tested pyzo2015a a moment ago).

**Comment by almarklein** [comment] 2016-09-15 22:33
I added a note to the website on how to run Pyzo the Linux way. Let's hope things work better with an update to Qt. If not, that'll be the best solution. Does that work for you (you might need `sudo` rights)?

**Comment by ysalmon** [comment] 2016-09-17 20:33
Are you talking about http://www.pyzo.org/install_linux.html#install-linux ?

One of the reasons I use pyzo and a separate miniconda installation is precisely to avoid using ``pip`` (which I find extremely cumbersome -- and I have yet to fathom why there are so many package managers ie. pip vs. conda) and especially mingling with my system python installation (as some important system tools are written in Python and I already found myself in dire because of this).

**Comment by almarklein** [comment] 2016-09-18 21:22
> Are you talking about http://www.pyzo.org/install_linux.html?

Yes. I understand its not perfect. Ideally you could do ` apt-get install pyzo` but we're not there yet. I will definitely try to update Qt/PyQt for the next binary release, but I suspect that running prebuild Qt apps on Linux will always have some quirks ...

**Comment by almarklein** [comment] 2016-09-27 10:07
This will be fixed with the new binaries. I can confirm that the cause was the font config not being found. As soon as I resolved that, the error disappeared and the loading was snappy again.

**Closed by almarklein** 2016-09-27 10:07 UTC
