### ISSUE TITLE
Version 4.11.4 cannot be started on Mac OS High Sierra

### ISSUE THREAD

**Issue by Corona21** [pyzo/pyzo#770] opened 2021-11-29 22:02 UTC
Mac OS High Sierra
Python 3.10 installed

scenario: double click on the app.
Observed behavior:
An error message is displayed: pyzo.app is damaged and can't be opened. You should move it to the Trash.

Note: version 4.11.2 can be opened without problem

**Comment by almarklein** [comment] 2021-11-30 08:42
Duplicate of #769

**Closed by almarklein** 2021-11-30 08:42 UTC
