### ISSUE TITLE
Pyzo and big sur 

### ISSUE THREAD

**Issue by operade** [pyzo/pyzo#734] opened 2020-11-18 21:36 UTC
Hi pyzo hangs on Big Sur (macOS 11.01) and is not responding. Any help would be appreciated. Thanks

**Comment by almarklein** [comment] 2020-11-18 21:37
Duplicate of #731

**Comment by almarklein** [comment] 2020-11-18 21:38
(see one of the bottom posts for a link to a working binary)

**Closed by almarklein** 2020-11-18 21:37 UTC
