### ISSUE TITLE
Support for pyqt6

### ISSUE THREAD

**Issue by stonebig** [pyzo/pyzo#779] opened 2021-12-21 18:05 UTC
Hoi,

Trying Pyzo  on https://github.com/pyzo/pyzo/commit/f26451356421c55038eb2092a6bc0913a8f004c1  with Windows 10

On Windows/PyQt6-6.2.2, it seems Pyzo-master of 2021-12-21-1700pm is not succeeding to fully start, on Windows
![image](https://user-images.githubusercontent.com/4312421/146976260-488c56c9-2de7-47fe-a69c-2e9aa218abe3.png)

on the Dos launching windows, I get this
![image](https://user-images.githubusercontent.com/4312421/146976501-c6d564d0-65f5-4d2b-b9ca-8b88ea62a9c2.png)

on PySide6-6.2.2, Pyzo-master of 2021-12-21-1700pm starts without issue
![image](https://user-images.githubusercontent.com/4312421/146976926-6e5fde12-f6d5-4441-9ff1-56119a80f239.png)

**Comment by stonebig** [comment] 2021-12-21 18:14
I would suspect it is because there is no 'TypeWriter' on Pyqt6-6.2.2, and maybe 'Courier' shall be the workaround (on Windows)

https://github.com/pyzo/pyzo/blob/main/pyzo/codeeditor/base.py#L403

trying to replace 
`font.setStyleHint(font.TypeWriter, font.PreferDefault)`
per
`font.setStyleHint(font.Courier, font.PreferDefault)`
...

**Comment by stonebig** [comment] 2021-12-21 18:25
then I fell one step further at:
![image](https://user-images.githubusercontent.com/4312421/146979979-f05c094c-3763-483c-b38c-5f0585486667.png)

**Comment by almarklein** [comment] 2021-12-21 19:58
In CI we now actually run Pyzo and close it after a few secs. With that I already found one or two other things that were changed in PyQt6. This error is new to me though, maybe because there is no build for Windows+pyqt6 at the moment. Would be good to extend that test to check for errors during the time Pyzo was running ...

What Python version is this with?

These look like errors that we should probably report/fix upstream to qtpy.

**Comment by stonebig** [comment] 2021-12-21 21:35
it's Python-3.10.1 64 bit Windows

**Comment by almarklein** [comment] 2022-01-13 20:48
I am indeed able to reproduce this on CI in #781 - all pyqt6 builds fail. We'd have to wait till qtpy has better support for pyqt6.

**Comment by almarklein** [comment] 2022-12-20 12:35
Related: I recently fixed Pyzo for PySide 6.4. PyQt6 is still not supported.

**Comment by almarklein** [comment] 2023-05-07 19:56
Closed by #854

**Closed by almarklein** 2023-05-07 19:56 UTC
